### ISSUE TITLE
Publish rocky-linux as dockerhub official image

### ISSUE THREAD

**Issue by srbala** [rocky-linux/sig-cloud-instance-images#1]
Team, please plan to publish rocky-linux as dockerhub official image

https://github.com/docker-library/official-images/tree/master/library

**Comment by NeilHanlon** [comment]
this is definitely in the plan for GA!

**Comment by srbala** [comment]
@NeilHanlon @jorp https://hub.docker.com/r/rockylinux/rockylinux/ community images count 100K, you can close this  issue

**Comment by NeilHanlon** [comment]
@srbala we're still looking to (at the very least) provide shortname support for rockylinux via https://github.com/containers/shortnames for example... as well as an official docker library image.

Going to keep this open to track. Sorry for the delay.. summer has been busy for the team(s)

**Comment by srbala** [comment]
@NeilHanlon thanks for the note/update

**Comment by NeilHanlon** [comment]
hi @srbala - we're now officially supported on Docker Hub - https://hub.docker.com/_/rockylinux
