### ISSUE TITLE
Rocky-linux-minimal docker image

### ISSUE THREAD

**Issue by srbala** [rocky-linux/sig-cloud-instance-images#2]
Team,

It would be good to have minimal image package, similar to `RedHatUBI-Minimal` with community support. The minimal compressed image closer to 40MB, uncompressed size around 105MB. it would 100MB+ smaller than regular package.

If interested let me know, I'll put together a PR

Thank you

**Comment by NeilHanlon** [comment]
@mstg thoughts here? not sure what we expect to be spit out of Koji

**Comment by mstg** [comment]
> @mstg thoughts here? not sure what we expect to be spit out of Koji 

Can't promise a more minimal than what we already have. Our current immage is small enough in my opinion. I'll look into it though.

**Comment by srbala** [comment]
Goal of minimal is to keep the package smaller, core runtime + minimal installer and its required packages only like following. https://catalog.redhat.com/software/containers/detail/5c359a62bed8bd75a2c3fba8

Main packages are
```
coreutils-single
microdnf
```

Following may be required for above packages.
```
rootfiles
bash
glibc-minimal-langpack
libusbx
```

**Comment by NeilHanlon** [comment]
I think realistically this is something we'll need to investigate post GA of 8.4. But if I recall correctly there were some others interested in UBI stuff. perhaps something the cloud sig can help work on

**Comment by jobcespedes** [comment]
Hi, 

With the Rocky Linux GA, we just added a minimal container image for it. We had it for Centos 8 minimal. It is based on Fedora Minimal and UBI 8. It is around ~35 MB (compressed) [This is the link](https://github.com/krestomatio/container_builder/tree/master/rocky8-minimal) of the repo/folder to build it and [this is the link](quay.io/krestomatio/rocky8-minimal) for the container image

**Comment by srbala** [comment]
Team, is this issue still needed, if no plans for minimal, you can close it.

**Comment by NeilHanlon** [comment]
@srbala I'd be happy to work on a minimal image.. perhaps @jobcespedes would permit the use of their minimal kickstart?

**Comment by jobcespedes** [comment]
No problem. It is open source and based on other projects.

**Comment by NeilHanlon** [comment]
I ended up making a minimal image, it's available at docker push neilresf/scratch:minimal while i'm testing.

Would appreciate any feedback! I'll up updating this repo soon with some scripts to generate container and cloud images.

**Comment by srbala** [comment]
@NeilHanlon minimal image `neilresf/scratch:minimal` looks good with my sanity verificaton looks good. Tested with docker and podman

**Comment by msierks-pcln** [comment]
@NeilHanlon The minimal image looks good to me.

**Comment by msierks-pcln** [comment]
@NeilHanlon When can we expect the scripts to generate the minimal container image?

**Comment by NeilHanlon** [comment]
Heya @msierks-pcln - Thanks for the patience, busy with prep for 8.6 and 9.

I've been reworking the image generation to be completely off-line (using systemd-nspawn via mkosi), which should considerably simplify the process for rebuilding and/or customizing, too. I'll be improving the documentation in the next couple weeks as well as getting these integrated to this pipeline for the images going to docker hub.

The 8.6 and 8.6-Minimal images were generated using this, too.

https://git.rockylinux.org/rocky/images/-/blob/main/base/scripts/build-container-rootfs.sh

**Comment by msierks** [comment]
@dejlek I believe it is intentional, you'll want to utilize **microdnf** instead.

**Comment by dejlek** [comment]
Thanks, microdnf is brilliant!
