### ISSUE TITLE
/tmp/ not writeable by all

### ISSUE THREAD

**Issue by gurka** [rocky-linux/sig-cloud-instance-images#22]
I'm not sure if this is the correct place to ask this, maybe this is an upstream thing, but starting from 8.6 (I think), the `/tmp/` directory is no longer writeable by all. It used to be 777 but now it's 755.

I tried to search if this was a change made in rockylinux 8.6 or RHEL 8.6 but couldn't find anything in changelogs, etc. Is it a change in how the docker image(s) are built?

Edit: actually it used to be 1777, not just 777. Also see https://unix.stackexchange.com/a/71625/80242

**Comment by NeilHanlon** [comment]
thanks for reporting this, I'll look into it this morning.

**Comment by jgosmann** [comment]
Any news? We've also stumbled upon this today.

**Comment by jgosmann** [comment]
I have a Rocky Linux 8.6 VM where the `/tmp` permissions are 1777. This makes me believe that the `8.5.20220308` image is broken.

**Comment by NeilHanlon** [comment]
Hi @gurka @jgosmann - I apologize for the latency in replying. New containers have been published to address these and other images. The proper permissions are 1777, as you noted.

Best,
Neil

**Comment by darxriggs** [comment]
@NeilHanlon
On https://hub.docker.com/_/rockylinux there is one 8.6 image that contains `20227707` in the tag instead of `20220707` which is a bit confusing.
On https://hub.docker.com/r/rockylinux/rockylinux all 8.6 images correctly contain `20220707`.
