### ISSUE TITLE
Error with localdef using rockylinux/rockylinux:8.6.20220515 docker image

### ISSUE THREAD

**Issue by phupe** [rocky-linux/sig-cloud-instance-images#24]
I have an error with localdef using `rockylinux/rockylinux:8.6.20220515` docker image while there is no error using `rockylinux:8.5`.

From the `rockylinux-8.5.Dockerfile` below, the `docker build -f rockylinux-8.5.Dockerfile -t rockylinux-8.5 .` command works:

```
FROM rockylinux/rockylinux:8.5

RUN dnf install -y epel-release \
        diffutils \
        langpacks-en glibc-langpack-en glibc-locale-source \
        procps-ng \
        which findutils \
        wget && \
    dnf clean all && \
    localedef --no-archive -i en_US -f UTF-8 en_US.UTF-8
```

While from the `rockylinux-8.6.20220515.Dockerfile`, the `docker build -f rockylinux-8.6.20220515.Dockerfile -t rockylinux-8.6.20220515 .` command fails:

```
FROM rockylinux/rockylinux:8.6.20220515

RUN dnf install -y epel-release \
        diffutils \
        langpacks-en glibc-langpack-en glibc-locale-source \
        procps-ng \
        which findutils \
        wget && \
    dnf clean all && \
    localedef --no-archive -i en_US -f UTF-8 en_US.UTF-8
```

The error message is the following:

```
[error] character map file `UTF-8' not found: No such file or directory
[error] default character map file `ANSI_X3.4-1968' not found: No such file or directory
```

Any idea to fix it?

**Comment by NeilHanlon** [comment]
Hi there,

This should be fixed now, I believe. Can you give it a try with the newest 8.6 container?

Best,
Neil

**Comment by phupe** [comment]
Hi Neil, thanks for the fix that perfectly works.

Best.
