### ISSUE TITLE
error building docker image from rockylinux:8.6-minimal

### ISSUE THREAD

**Issue by cd-blank** [rocky-linux/sig-cloud-instance-images#33]
error while trying to build docker image from rocky linux 8.6 minimal but success with rockylinux:8.6

<img width="631" alt="image" src="https://user-images.githubusercontent.com/12499184/181476474-fe1ca896-f0fb-4943-98f7-f9853d79878b.png">

**Comment by NeilHanlon** [comment]
The minimal image uses microdnf instead of dnf/yum. please try using the microdnf command in place of 'yum' in your builds.

**Comment by xf74** [comment]
oke thanks

**Comment by cd-blank** [comment]
> The minimal image uses microdnf instead of dnf/yum. please try using the microdnf command in place of 'yum' in your builds.

@NeilHanlon thank you very much
