### ISSUE TITLE
Error with localdef using rockylinux/rockylinux:9.1 docker image

### ISSUE THREAD

**Issue by phupe** [rocky-linux/sig-cloud-instance-images#37]
Hi @NeilHanlon ,

I guess we have the same issue as described is Issue #24.

I have an error with localdef using `rockylinux/rockylinux:9.1 docker image while there is no error using `rockylinux:9.0`.

From the `rockylinux-9.0.Dockerfile` below, the `docker build -f rockylinux-9.0.Dockerfile -t rockylinux-9.0 .` command works:

```
FROM rockylinux/rockylinux:9.0

RUN dnf install -y epel-release \
        diffutils \
        langpacks-en glibc-langpack-en glibc-locale-source \
        procps-ng \
        which findutils \
        wget && \
    dnf clean all && \
    localedef --no-archive -i en_US -f UTF-8 en_US.UTF-8
```

While from the `rockylinux-9.1.Dockerfile`, the `docker build -f rockylinux-9.1.Dockerfile -t rockylinux-9.1 .` command fails:

```
FROM rockylinux/rockylinux:9.1

RUN dnf install -y epel-release \
        diffutils \
        langpacks-en glibc-langpack-en glibc-locale-source \
        procps-ng \
        which findutils \
        wget && \
    dnf clean all && \
    localedef --no-archive -i en_US -f UTF-8 en_US.UTF-8
```

The error message is the following:

```
[error] character map file `UTF-8' not found: No such file or directory
[error] default character map file `ANSI_X3.4-1968' not found: No such file or directory
```

Would it be possible to fix it? Thanks.

**Comment by missedone** [comment]
have the same issue, it looks to me a breaking change not mentioned in the image release notes

**Comment by NeilHanlon** [comment]
Thank you for the report @phupe and for the ping on the issue @missedone

I am releasing a new version of the container which addresses this properly. Apologies for the regression.

I'll update this ticket when the images are live

--Neil

**Comment by NeilHanlon** [comment]
Hi all - the latest official images should be all set now. Thank you!

**Comment by missedone** [comment]
@NeilHanlon 

i still see the issue on image tag `9-minimal`
> #0 37.24 [error] character map file `UTF-8' not found: No such file or directory
#0 37.63 [error] default character map file `ANSI_X3.4-1968' not found: No such file or directory

BTW, i noticed the image was updated 2 days ago, could you confirm if i was using the right image tag?
![image](https://user-images.githubusercontent.com/555134/208978709-6f2b1a3d-2c52-498a-9bba-a2a67a669b7a.png)

**Comment by NeilHanlon** [comment]
Ah, good catch. My PR went through but the images haven't finished building yet. Let's wait until they are published today.

**Comment by missedone** [comment]
@NeilHanlon i can confirm the issue is solved once use the latest image , thanks for your help.

**Comment by phupe** [comment]
Thanks @NeilHanlon, it works fine for me!
