### ISSUE TITLE
rocky linux as cloud image

### ISSUE THREAD

**Issue by sebastian-schmid** [rocky-linux/sig-cloud-instance-images#4]
Rocky Linux cloud images like https://cloud.debian.org/images/cloud/ would be very useful. 

Do you plan to provide cloud images for the following provider or some of them?

- [x]  OpenStack -> https://dl.rockylinux.org/pub/rocky/8.4/images/
- [x]  AWS
- [x]  GCP -> official supported Image available on GCE
- [x]  Azure

**Comment by aminvakil** [comment]
I just asked this on #rockylinux IRC channel in Libera and it exists.
https://dl.rockylinux.org/pub/rocky/8.4/images/

**Comment by mstg** [comment]
As @aminvakil points out, we do currently have an OpenStack-compatible image. It's aarch64 variant will be published very soon. There has been some delays with the AWS team, but we're expecting to see the images very soon. You can already launch Rocky instances on GCE (It's an officially supported image). Azure is also in the works so stay tuned! I can let this issue stay open until we have all those in place.

**Comment by sebastian-schmid** [comment]
This is great, thank you for the link @aminvakil and information @mstg

**Comment by RobVerduijn** [comment]
@mstg

Hi, is there also an image for libvirt ?

I tried the image at [https://dl.rockylinux.org/pub/rocky/8.4/images/](https://dl.rockylinux.org/pub/rocky/8.4/images/) but that one complains that it can't find the kernel.

**Comment by tbugfinder** [comment]
Any update on Azure?

**Comment by NeilHanlon** [comment]
All of these providers are available and the sources for the images published in any marketplaces will be available as well going forward in the images/ directory in our repositories.

I will close this issue out for now. If other clouds are wanted, please open issues for each individual one. To note, Oracle Cloud as well as IBM Cloud should be in the works!
